import argparse
import csv
import glob
import json
import math
import os
import re
import shutil
import shlex
import subprocess
import sys

sys.path.append(".")

import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem

from utils.evaluation.scoring_func import get_chem


FLOAT_RE = re.compile(r"[-+]?(?:\d+\.\d*|\.\d+|\d+)(?:[Ee][-+]?\d+)?")


def find_sdf_dir(run_dir):
    candidates = sorted(glob.glob(os.path.join(run_dir, "*_SDF")))
    if not candidates:
        raise FileNotFoundError("No *_SDF directory found under %s" % run_dir)
    if len(candidates) > 1:
        raise ValueError("Multiple *_SDF directories found: %s" % ", ".join(candidates))
    return candidates[0]


def numeric_sdf_key(path):
    stem = os.path.splitext(os.path.basename(path))[0]
    try:
        return int(stem)
    except ValueError:
        return stem


def iter_candidate_sdfs(sdf_dir):
    paths = []
    for path in glob.glob(os.path.join(sdf_dir, "*.sdf")):
        if os.path.basename(path).startswith("traj_"):
            continue
        paths.append(path)
    return sorted(paths, key=numeric_sdf_key)


def safe_name(text):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", text)


def read_mol(path, sanitize=True):
    mol = Chem.SDMolSupplier(path, removeHs=False, sanitize=sanitize)[0]
    if mol is None and sanitize:
        mol = Chem.SDMolSupplier(path, removeHs=False, sanitize=False)[0]
    if mol is None:
        raise ValueError("RDKit failed to read %s" % path)
    if mol.GetNumConformers() == 0:
        mol = Chem.AddHs(mol)
        AllChem.EmbedMolecule(mol, AllChem.ETKDGv3())
    if sanitize:
        try:
            Chem.SanitizeMol(mol)
        except Exception:
            pass
    return mol


def mol_to_xyz(mol, xyz_path):
    mol = Chem.AddHs(mol, addCoords=True)
    conf = mol.GetConformer()
    with open(xyz_path, "w") as f:
        f.write("%d\n" % mol.GetNumAtoms())
        f.write("generated by frequency_rerank.py\n")
        for atom in mol.GetAtoms():
            pos = conf.GetAtomPosition(atom.GetIdx())
            f.write(
                "%-3s % .8f % .8f % .8f\n"
                % (atom.GetSymbol(), pos.x, pos.y, pos.z)
            )


def run_cmd(cmd, cwd, timeout):
    try:
        result = subprocess.run(
            cmd,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True,
            timeout=timeout,
        )
        return result.returncode, result.stdout
    except subprocess.TimeoutExpired as exc:
        output = exc.stdout or ""
        if isinstance(output, bytes):
            output = output.decode(errors="ignore")
        return 124, output + "\nTIMEOUT after %d seconds\n" % timeout


def parse_vibspectrum(path):
    freqs = []
    intensities = []
    with open(path, "r", errors="ignore") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or stripped.startswith("$"):
                continue
            nums = [float(x) for x in FLOAT_RE.findall(stripped)]
            if not nums:
                continue
            first = stripped.split()[0]
            if first.lstrip("+-").isdigit() and len(nums) >= 2:
                freq = nums[1]
                intensity = nums[2] if len(nums) >= 3 else 1.0
            else:
                freq = nums[0]
                intensity = nums[1] if len(nums) >= 2 else 1.0
            if abs(freq) < 10000:
                freqs.append(freq)
                intensities.append(max(float(intensity), 0.0))
    return freqs, intensities


def parse_xtb_frequency_stdout(text):
    freqs = []
    for line in text.splitlines():
        if "cm" not in line.lower():
            continue
        nums = [float(x) for x in FLOAT_RE.findall(line)]
        for num in nums:
            if -1000.0 < num < 5000.0:
                freqs.append(num)
    return freqs, [1.0 for _ in freqs]


def compute_xtb_frequencies(
    sdf_path,
    work_dir,
    xtb_cmd,
    gfn,
    timeout,
    force=False,
):
    os.makedirs(work_dir, exist_ok=True)
    cache_path = os.path.join(work_dir, "frequencies.json")
    if os.path.exists(cache_path) and not force:
        with open(cache_path, "r") as f:
            return json.load(f)

    mol = read_mol(sdf_path, sanitize=False)
    try:
        charge = int(Chem.GetFormalCharge(mol))
    except Exception:
        charge = 0
    xyz_path = os.path.join(work_dir, "input.xyz")
    mol_to_xyz(mol, xyz_path)

    cmd_base = shlex.split(xtb_cmd)
    opt_cmd = cmd_base + ["input.xyz", "--gfn", str(gfn), "--opt", "--chrg", str(charge)]
    opt_code, opt_out = run_cmd(opt_cmd, cwd=work_dir, timeout=timeout)
    with open(os.path.join(work_dir, "xtb_opt.log"), "w", errors="ignore") as f:
        f.write(opt_out)

    hess_input = "xtbopt.xyz" if os.path.exists(os.path.join(work_dir, "xtbopt.xyz")) else "input.xyz"
    hess_cmd = cmd_base + [hess_input, "--gfn", str(gfn), "--hess", "--chrg", str(charge)]
    hess_code, hess_out = run_cmd(hess_cmd, cwd=work_dir, timeout=timeout)
    with open(os.path.join(work_dir, "xtb_hess.log"), "w", errors="ignore") as f:
        f.write(hess_out)

    freqs = []
    intensities = []
    vib_path = os.path.join(work_dir, "vibspectrum")
    if os.path.exists(vib_path):
        freqs, intensities = parse_vibspectrum(vib_path)
    if not freqs:
        freqs, intensities = parse_xtb_frequency_stdout(hess_out)

    positive_freqs = [float(f) for f in freqs if f > 0]
    positive_intensities = [
        float(i) for f, i in zip(freqs, intensities) if f > 0
    ]
    imaginary_count = sum(1 for f in freqs if f < 0)

    result = {
        "sdf_path": sdf_path,
        "charge": charge,
        "opt_returncode": opt_code,
        "hess_returncode": hess_code,
        "frequencies": positive_freqs,
        "intensities": positive_intensities,
        "imaginary_count": imaginary_count,
        "n_frequencies": len(positive_freqs),
        "status": "ok" if positive_freqs else "failed",
    }
    with open(cache_path, "w") as f:
        json.dump(result, f, indent=2)
    return result


def spectrum_vector(freqs, intensities, grid_min, grid_max, grid_step, sigma):
    grid = np.arange(grid_min, grid_max + grid_step, grid_step, dtype=float)
    vec = np.zeros_like(grid, dtype=float)
    if not freqs:
        return grid, vec
    if not intensities or len(intensities) != len(freqs) or sum(intensities) <= 0:
        intensities = [1.0 for _ in freqs]
    for freq, intensity in zip(freqs, intensities):
        vec += float(intensity) * np.exp(-0.5 * ((grid - float(freq)) / sigma) ** 2)
    norm = np.linalg.norm(vec)
    if norm > 0:
        vec = vec / norm
    return grid, vec


def cosine_similarity(a, b):
    denom = float(np.linalg.norm(a) * np.linalg.norm(b))
    if denom == 0:
        return None
    return float(np.dot(a, b) / denom)


def load_metrics_csv(path):
    metrics = {}
    if not path or not os.path.exists(path):
        return metrics
    with open(path, "r", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            mol_id = row.get("mol_id")
            if mol_id is not None:
                metrics[str(mol_id)] = row
    return metrics


def load_sample_log(sdf_dir):
    metrics = {}
    path = os.path.join(sdf_dir, "log.txt")
    if not os.path.exists(path):
        return metrics
    with open(path, "r", errors="ignore") as f:
        lines = [line.strip() for line in f if line.strip()]
    for line in lines[1:]:
        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 6:
            continue
        mol_id, smiles, sa, qed, vina, score = parts[:6]
        metrics[str(mol_id)] = {
            "mol_id": mol_id,
            "smiles": smiles,
            "sa": sa,
            "qed": qed,
            "vina_score_only": vina,
            "score": score,
        }
    return metrics


def to_float(value):
    try:
        if value in ("", None):
            return None
        value = float(value)
        if math.isnan(value):
            return None
        return value
    except (TypeError, ValueError):
        return None


def minmax(values):
    numeric = [v for v in values if v is not None]
    if not numeric:
        return [None for _ in values]
    lo, hi = min(numeric), max(numeric)
    if abs(hi - lo) < 1e-12:
        return [0.5 if v is not None else None for v in values]
    return [(v - lo) / (hi - lo) if v is not None else None for v in values]


def add_final_scores(rows, weights):
    components = {
        "freq_component": [to_float(r.get("freq_similarity")) for r in rows],
        "vina_component": [
            -to_float(r.get("vina_score_only")) if to_float(r.get("vina_score_only")) is not None else None
            for r in rows
        ],
        "qed_component": [to_float(r.get("qed")) for r in rows],
        "sa_component": [
            -to_float(r.get("sa")) if to_float(r.get("sa")) is not None else None
            for r in rows
        ],
    }
    normalized = {name: minmax(vals) for name, vals in components.items()}

    for idx, row in enumerate(rows):
        total = 0.0
        used = 0.0
        for name, weight in weights.items():
            value = normalized[name][idx]
            if value is None:
                continue
            row[name] = value
            total += weight * value
            used += weight
        row["final_score"] = total / used if used > 0 else None


def format_float(value):
    value = to_float(value)
    if value is None:
        return ""
    return "%.6f" % value


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--run_dir", type=str, default=None)
    parser.add_argument("--sdf_dir", type=str, default=None)
    parser.add_argument("--target_sdf", type=str, required=True)
    parser.add_argument("--metrics_csv", type=str, default=None)
    parser.add_argument("--out", type=str, default=None)
    parser.add_argument("--work_dir", type=str, default=None)
    parser.add_argument("--xtb_cmd", type=str, default="xtb")
    parser.add_argument("--gfn", type=int, default=2)
    parser.add_argument("--timeout", type=int, default=900)
    parser.add_argument("--grid_min", type=float, default=0.0)
    parser.add_argument("--grid_max", type=float, default=4000.0)
    parser.add_argument("--grid_step", type=float, default=10.0)
    parser.add_argument("--sigma", type=float, default=50.0)
    parser.add_argument("--w_freq", type=float, default=0.45)
    parser.add_argument("--w_vina", type=float, default=0.30)
    parser.add_argument("--w_qed", type=float, default=0.15)
    parser.add_argument("--w_sa", type=float, default=0.10)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    if shutil.which(shlex.split(args.xtb_cmd)[0]) is None:
        raise FileNotFoundError(
            "xTB command not found: %s. Install xTB first or pass --xtb_cmd." % args.xtb_cmd
        )

    if args.sdf_dir is None and args.run_dir is None:
        raise ValueError("Please provide either --sdf_dir or --run_dir")
    sdf_dir = args.sdf_dir or find_sdf_dir(args.run_dir)
    run_dir = args.run_dir or os.path.dirname(sdf_dir)
    work_dir = args.work_dir or os.path.join(run_dir, "freq_work")
    out = args.out or os.path.join(run_dir, "frequency_rerank.csv")

    metrics_csv = args.metrics_csv or os.path.join(run_dir, "sdf_eval.csv")
    metrics = load_metrics_csv(metrics_csv)
    if not metrics:
        metrics = load_sample_log(sdf_dir)

    os.makedirs(work_dir, exist_ok=True)
    target_freq = compute_xtb_frequencies(
        args.target_sdf,
        os.path.join(work_dir, "target_" + safe_name(os.path.splitext(os.path.basename(args.target_sdf))[0])),
        args.xtb_cmd,
        args.gfn,
        args.timeout,
        force=args.force,
    )
    _, target_vec = spectrum_vector(
        target_freq["frequencies"],
        target_freq["intensities"],
        args.grid_min,
        args.grid_max,
        args.grid_step,
        args.sigma,
    )
    target_spectrum_path = os.path.join(run_dir, "frequency_target_spectrum.json")
    grid = np.arange(args.grid_min, args.grid_max + args.grid_step, args.grid_step, dtype=float)
    with open(target_spectrum_path, "w") as f:
        json.dump(
            {
                "source_sdf": args.target_sdf,
                "grid_min": args.grid_min,
                "grid_max": args.grid_max,
                "grid_step": args.grid_step,
                "sigma": args.sigma,
                "grid": grid.tolist(),
                "spectrum": target_vec.tolist(),
                "frequencies": target_freq["frequencies"],
                "intensities": target_freq["intensities"],
            },
            f,
            indent=2,
        )

    rows = []
    for sdf_path in iter_candidate_sdfs(sdf_dir):
        mol_id = os.path.splitext(os.path.basename(sdf_path))[0]
        row = {
            "mol_id": mol_id,
            "sdf_path": sdf_path,
        }
        row.update(metrics.get(str(mol_id), {}))
        if "smiles" not in row or not row["smiles"]:
            try:
                row["smiles"] = Chem.MolToSmiles(read_mol(sdf_path, sanitize=True))
            except Exception:
                row["smiles"] = ""
        chem_keys = ["qed", "sa", "logp", "lipinski", "tpsa"]
        if any(k not in row or row[k] in ("", None) for k in chem_keys):
            try:
                chem = get_chem(read_mol(sdf_path, sanitize=True))
                for key in chem_keys:
                    if key not in row or row[key] in ("", None):
                        row[key] = chem[key]
            except Exception as exc:
                row["chem_error"] = repr(exc)

        try:
            freq = compute_xtb_frequencies(
                sdf_path,
                os.path.join(work_dir, "mol_" + safe_name(mol_id)),
                args.xtb_cmd,
                args.gfn,
                args.timeout,
                force=args.force,
            )
            _, vec = spectrum_vector(
                freq["frequencies"],
                freq["intensities"],
                args.grid_min,
                args.grid_max,
                args.grid_step,
                args.sigma,
            )
            row["freq_similarity"] = cosine_similarity(vec, target_vec)
            row["n_frequencies"] = freq["n_frequencies"]
            row["imaginary_count"] = freq["imaginary_count"]
            row["xtb_status"] = freq["status"]
        except Exception as exc:
            row["freq_similarity"] = ""
            row["n_frequencies"] = 0
            row["imaginary_count"] = ""
            row["xtb_status"] = "failed"
            row["error"] = repr(exc)
        rows.append(row)

    weights = {
        "freq_component": args.w_freq,
        "vina_component": args.w_vina,
        "qed_component": args.w_qed,
        "sa_component": args.w_sa,
    }
    add_final_scores(rows, weights)
    rows.sort(
        key=lambda r: (
            to_float(r.get("final_score")) is not None,
            to_float(r.get("final_score")) or -1e9,
        ),
        reverse=True,
    )
    for idx, row in enumerate(rows, 1):
        row["rank"] = idx

    fieldnames = [
        "rank",
        "mol_id",
        "sdf_path",
        "smiles",
        "final_score",
        "freq_similarity",
        "vina_score_only",
        "vina_min",
        "qed",
        "sa",
        "logp",
        "lipinski",
        "tpsa",
        "n_frequencies",
        "imaginary_count",
        "xtb_status",
        "freq_component",
        "vina_component",
        "qed_component",
        "sa_component",
        "score",
        "error",
        "chem_error",
    ]
    with open(out, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            formatted = dict(row)
            for key in [
                "final_score",
                "freq_similarity",
                "vina_score_only",
                "vina_min",
                "qed",
                "sa",
                "logp",
                "lipinski",
                "tpsa",
                "freq_component",
                "vina_component",
                "qed_component",
                "sa_component",
                "score",
            ]:
                if key in formatted:
                    formatted[key] = format_float(formatted[key])
            writer.writerow(formatted)

    print("Saved:", out)
    print("Target spectrum:", target_spectrum_path)
    print("Target frequencies:", target_freq["n_frequencies"])
    print("Ranked molecules:", len(rows))
    for row in rows[:10]:
        print(
            "rank=%s mol=%s final=%s freq=%s vina=%s qed=%s sa=%s"
            % (
                row["rank"],
                row["mol_id"],
                format_float(row.get("final_score")),
                format_float(row.get("freq_similarity")),
                format_float(row.get("vina_score_only")),
                format_float(row.get("qed")),
                format_float(row.get("sa")),
            )
        )


if __name__ == "__main__":
    main()
